[tool.ruff]
line-length = 150
target-version = "py311"
ignore = ["B008","E722","B904"]

[tool.ruff.lint.per-file-ignores]
"tests/conftest.py" = ["E402"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]

[tool.black]
line-length = 150
target-version = ["py311"]
