name: Deploy Service resource

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'action to be performed'
        required: true
        default: 'apply-action'
        type: choice
        options:
          - "apply-action"
          - "destroy-action"

env:
  TF_VERSION: '1.14.4'
  AWS_REGION: 'us-east-1'

jobs:
  deployment:
    if: inputs.action == 'apply-action'
    name: Deploy Service
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        working-directory: infra/terraform/service

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup terraform variables
        id: vars
        run: |-
          cat > terraform.tfvars <<EOF
          AWS_REGION="${{ env.AWS_REGION }}"
          EOF

      - name: Terraform Init
        run: terraform init -backend-config=../envs/dev/backend.hcl

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

  destroy:
    if: inputs.action == 'destroy-action'
    name: Destroy Service
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        working-directory: infra/terraform/service

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup terraform variables
        id: vars
        run: |-
          cat > terraform.tfvars <<EOF
          AWS_REGION="${{ env.AWS_REGION }}"
          CLUSTER_ARN="${{ vars.CLUSTER_ARN }}"
          APP_IMAGE_NAME="${{ vars.APP_IMAGE_NAME }}"
          APP_ROLE_ARN="${{ vars.APP_ROLE_ARN }}"
          EOF

      - name: Terraform Init
        run: terraform init -backend-config=../envs/dev/backend.hcl

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
